welcome_message: |
  *SoundPass Bot* — это удобный и надежный способ оформить подписку на Spotify Premium 

  *Преимущества:*

  → Оформление подписки за несколько минут  
  → Полный доступ к Spotify без рекламы и ограничений  
  → Прозрачные тарифы и удобная оплата  
  → Надежность и безопасность  

  Выберите подходящий тариф и *наслаждайтесь музыкой без перерыва* 🎧

subscription_message: "Выберите подписку:"
payment_message: "Оплатить подписку:"
processing_payment_message: "🔄 Мы обрабатываем ваш платеж. Совсем скоро вы сможете пользоваться Spotify! 🎶"
thank_you_message: "Ваши данные сохранены. Спасибо за покупку!"

login: "Введите ваш логин от Spotify:"
password: "Введите ваш пароль от Spotify:"